//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebApiEfExample.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class EmployeeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeTable()
        {
            this.EmployeeTable1 = new HashSet<EmployeeTable>();
        }
    
        [DataMember]
        public int Eid { get; set; }
        [DataMember]
        public string Ename { get; set; }
        [DataMember]
        public Nullable<int> Salary { get; set; }
        [DataMember]

        public string gender { get; set; }
        public Nullable<int> de_id { get; set; }
        public Nullable<int> mgid { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTable> EmployeeTable1 { get; set; }
        public virtual EmployeeTable EmployeeTable2 { get; set; }
    }
}
