//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjAPIDepartEmployee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public int Eid { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> salary { get; set; }
        public string mobile { get; set; }
        public string Password { get; set; }
        public Nullable<int> Deptid { get; set; }
    
        public virtual DepartmentTable DepartmentTable { get; set; }
    }
}
